# Header Menu
menu:
    Home: /
    Blog: /blog/ # can set archive-dir in root config to custom value
    Services: https://hub.vectordigi.cc
    Contact: /contact/

rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true # whether or not to load the fancybox library

# Integrations
disqus_shortname: 
google_analytics:
swiftype_install_key: 

# Social
social:
    github: https://github.com/di-gigen
    twitter: 
    facebook: 
    rss: atom.xml
    linkedin: 
    stackoverflow: 

# Miscellaneous
color_scheme: red   # options: blue, gray, green, orange, red, turquoise
favicon: /favicon.ico # path from root of hexo site
twitter_username: # twitter username without the @
default_author: hostmaster

about: 數位研是由社区驱动的自由软件与DIY硬件开发组织, 成立于2012年. <br> 我们以自身行动抵制数字领域利用不对等体量行使侵权行为的产品和服务.
phone: 707-242-1889
email: vectordigi@disroot.org
address_1: California
address_2: Earth
address_3: Sector 2814
skype: 
lat: 
long: 
